data:
  dataset: "BTCV"
  data_dir: "../medopenseg/datasets/BTCV/"
  split_json: "swin_unetr_btcv_dataset_0.json"

model:
  in_channels: 1
  out_channels: 11  # Background (0) + 10 Known Organs
  feature_size: 48  
  embed_dim_final: 128 

training:
  batch_size: 2
  lr: 1e-4
  max_iterations: 43000
  eval_num: 100  # Runs validation every 100 epochs (approx 1200 steps)
  checkpoint_dir: "./outputs/btcv/btcv_gated_weighted_fix"
  pretrained_weights: "./weights/model_swinvit.pt"

  resume: True 

  vmf:
    tau: 1.0
    reject_weight: 0.2
    include_background: True

    # Schedule in STEPS
    warmup_steps: 9600      # ~epoch 800 (Pure Segmentation + Silent Memory Update)
    ramp_steps: 2400        # ~epoch 1000 (vMF fully active)
    max_weight: 0.05        # Conservative weight for LogSumExp loss
    
    # CRITICAL: Must be False so memory is ready at step 9600
    delay_memory_updates: False 
  
  use_memory_bank: True  
  memory_size: 500